name: 6.18

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-kernel.yml
    with:
      pkgver: 6.18.13.arch1-1
