name: 7.1 stable

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-kernel.yml
    with:
      pkgver: 7.1.2.arch3-1
